name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Angular Github Actions
      # You may pin to the exact commit or the version.
      # uses: mayurrawte/github-angular-actions@babc38d81371a05fbe9b9b6d50d241efb96d4faf
      uses: mayurrawte/github-angular-actions@latest
    - name: Angular Deploy gh-pages Actions
      # You may pin to the exact commit or the version.
      # uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        # Github access token token used to deploy on gh_pages. You can find it on Github.
        github_access_token: ${{ secrets.TOKEN_GITHUB_ACTION }}
        # The directory of the angular project, in which all the commands will run
        angular_project_dir: ./
        # Build configuration for the angular app
        build_configuration: production
        # base href for the app
        base_href: /
        # branch on which the angular build will be deployed
        deploy_branch: gh-pages
        # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
        angular_dist_build_folder: /docs
        # If the action should run 'ng lint'
        # Will not fail the step if anything fails
        skip_failure: true 
    - name: Heroku Action
      # You may pin to the exact commit or the version.
      # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: 617b3d0c-2f9a-4b75-a8ff-a04e0a8bba4c
        # Email from Heroku Account
        heroku_email: evanhaggard123@gmail.com
        # The appname to use for deploying/updating
        heroku_app_name: himediahub
        # The branch that you would like to deploy to Heroku
        branch: master
        # Set this to true if want to use --force
        useforce: false
        # Set if your app is located in a subdirectory.
        dynamicFiles: true
        # Buildpacks to install on Heroku


   

