name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Angular Github Actions
      # You may pin to the exact commit or the version.
      # uses: mayurrawte/github-angular-actions@babc38d81371a05fbe9b9b6d50d241efb96d4faf
      uses: mayurrawte/github-angular-actions@latest
    - name: Angular Deploy gh-pages Actions
      # You may pin to the exact commit or the version.
      # uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        # Github access token token used to deploy on gh_pages. You can find it on Github.
        github_access_token: ${{ secrets.TOKEN_GITHUB_ACTION }}
        # The directory of the angular project, in which all the commands will run
        angular_project_dir: ./
        # Build configuration for the angular app
        build_configuration: production
        # base href for the app
        base_href: /
        # branch on which the angular build will be deployed
        deploy_branch: gh-pages
        # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
        angular_dist_build_folder: /docs
        # If the action should run 'ng lint'
        # Will not fail the step if anything fails
        skip_failure: true    

